version: '3.8'

services:
  nginx:
    build: ./nginx
    image: harbor01.cssnr.com/shane/discord-sync-docker-nginx:${VERSION}
    env_file: ${ENV_FILE}
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    depends_on:
      - app
    secrets:
      - source: cssnr.com.crt
        target: /etc/ssl/cssnr.com.crt
      - source: cssnr.com.key
        target: /etc/ssl/cssnr.com.key
      - source: cssnr_basic_http_auth
        target: /etc/nginx/auth.users
    ports:
      - "${DOCKER_PORT}:443"
    links:
      - "app"
      - "flower"

  app:
    build: ./app
    image: harbor01.cssnr.com/shane/discord-sync-docker-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "gunicorn discordsync.wsgi:application -w 2 -b 0.0.0.0:9000"
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    depends_on:
      - redis

  worker:
    image: harbor01.cssnr.com/shane/discord-sync-docker-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "celery -A discordsync worker -l INFO -c 2"
    deploy:
      replicas: 1
    depends_on:
      - app
      - redis

  beat:
    image: harbor01.cssnr.com/shane/discord-sync-docker-app:${VERSION}
    env_file: ${ENV_FILE}
    command: "celery -A discordsync beat -l INFO -s /celerybeat-schedule"
    deploy:
      replicas: 1
    depends_on:
      - app
      - redis

  redis:
    image: redis:6-alpine
    deploy:
      replicas: 1
    volumes:
      - redis_data:/data

  flower:
    image: mher/flower
    env_file: ${ENV_FILE}
    deploy:
      replicas: 1
    volumes:
      - flower_data:/data

secrets:
  cssnr.com.crt:
    external: true
  cssnr.com.key:
    external: true
  cssnr_basic_http_auth:
    external: true

volumes:
  data_dir:
  redis_data:
  flower_data:
